---
loggly:
  token: "{{ secrets.loggly.token }}"
  certificate_url: https://logdog.loggly.com/media/logs-01.loggly.com_sha12.crt
  certificate_file: logs-01.loggly.com_sha12.crt
  certificate_dest: /etc/rsyslog.d/keys/ca.d/
  rsyslog_version: 8
  rsyslog_ppa: ppa:adiscon/v8-stable
  application:
    tag: Rails
    logs: []
  nginx:
    access_logs:
      - /var/log/nginx/access.log
    error_logs:
      - /var/log/nginx/error.log
  action_queue_max_disk_space: 250m
  logrotate: true
