---
- hosts: aws
  tasks:
    - name: test
      command: node --version
    - name: Run DB Fixtures
      command: node db2.js
      become: yes
      become_user: notejam
      args:
        chdir: /home/notejam/app/express/notejam
      environment:
        DB_CONNECTION: "mysql://{{ root_db_user }}:{{ root_db_password }}@{{ app_db_host }}:3306/{{ app_db_name }}"

