---
- fail: msg="This role requires 'loggly.token'"
  when: loggly.token | trim == ''

- include: v8.yml
  when: ansible_distribution == "Ubuntu" and loggly.rsyslog_version|int > 7

- include: v7.yml
  when: loggly.rsyslog_version|int < 8

- include: logrotate.yml
  when: loggly.logrotate

- apt: name={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - rsyslog
    - rsyslog-gnutls

- name: Create cerfiticates folder If It Does Not Exist
  file: path={{ loggly.certificate_dest }} state=directory

- name: Install loggly certificate bundle once https://en.wikipedia.org/wiki/Server_Name_Indication is supported
  get_url: url={{ loggly.certificate_url }} dest={{ loggly.certificate_dest }}{{ loggly.certificate_file }}
  ignore_errors: yes

- name: Ensure wget is installed until SNI is supported
  apt: name=wget update_cache=yes cache_valid_time=3600

- name: Use wget cause Python 2.7.6 doesn't support https://en.wikipedia.org/wiki/Server_Name_Indication
  command: wget -O {{ loggly.certificate_dest }}{{ loggly.certificate_file }} {{ loggly.certificate_url }}
  notify:
    - restart_rsyslog

- name: Disable $KLogPermitNonKernelFacility configuration (this option is deprecated)
  lineinfile: dest=/etc/rsyslog.conf state=absent regexp='^\$KLogPermitNonKernelFacility'

# using shell until file: state=absent works the same as below
- name: Cleanup files that may have been left by other installations
  shell: rm -f /etc/rsyslog.d/*-loggly-*

- name: Ensure nginx dir exists for rsyslogd
  file: name=/var/log/nginx state=directory

- name: Add Rsyslog configuration file
  template: src="{{ item }}" dest="/etc/rsyslog.d/{{ item }}" owner=root group=root
  with_items:
    - 21-loggly-base.conf
    - 22-loggly-nginx.conf
    - 22-loggly-application.conf
    - 23-loggly-rsyslog_tls.conf
  notify:
    - restart_rsyslog
